# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8af9b0856da22541e08d0d447ee835fc2c942867a6b637f1e8944f11947fc85cfaad75f3f061e4544edc125ed68e21011dabf55c461f88e8bb8207d31e7437cb

test:
  secret_key_base: 90026629d2cdaa09ff7f420b5088a359cbd055ef75577dc050370f4362982dbc131c34538c0ae9ac40a1c5c51676be5c094825399ae92121860e332e8a528cb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
